server:
  port: 8083
  http2:
    enabled: true
spring:
  application:
    name: bs-orders
  datasource:
    url: jdbc:postgresql://${ORDER_DB_HOST}:${ORDER_DB_PORT}/${ORDER_DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: false
    hostname: bs-orders
service:
  catalog:
    url: 'http://localhost:8081'
  clients:
    url: 'http://localhost:8082'