server:
  port: 8083
  http2:
    enabled: true
spring:
  application:
    name: bs-orders
  datasource:
    #url: jdbc:postgresql://${ORDER_DB_HOST}:${ORDER_DB_PORT}/${ORDER_DB_NAME}
    #username: ${DB_USERNAME}
    #password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5433/ORDERS_DB
    username: postgres
    password: 12345
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
  instance:
    prefer-ip-address: false
    hostname: localhost
service:
  catalog:
    url: 'http://bs-catalog/%s'
  clients:
    url: 'http://bs-clients/%s'